---
title: "profiling_code"
format: html
editor: visual
---

```{r}
library(data.table)
library(purrr)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(MOFA2)
library(here)
library(profvis)
source(here('MCMC_Algorithms', 'run_mcmc_UGLT_Static.R'))
set.seed(1)
```

```{r}
dt <- fread("ftp://ftp.ebi.ac.uk/pub/databases/mofa/microbiome/data.txt.gz")
metadata <- fread("ftp://ftp.ebi.ac.uk/pub/databases/mofa/microbiome/metadata.txt.gz")
head(dt)
```

You can add options to executable code like this

```{r}
dt_bact = dt[dt$view == 'Bacteria', ]
head(dt_bact)
```

```{r}
dt_bact = dt_bact |> tidyr::pivot_wider(names_from = sample, values_from = 'value') |> dplyr::select(-c('view'))
```

```{r}
head(dt_bact)
```

```{r}
# Now fitting the bayesian factor model. Let's just try to use a static model with 10 factors.
V = dim(dt_bact)[1]

profile_1 = profvis::profvis(run_mcmc_UGLT(N = (dim(dt_bact)[2] - 1), q = 10, n_runs = 1000, alpha = rep(1, V),
  beta = rep(1, V), theta.shape = rep(1.5, V), theta.rate = rep(1.5, V), hyperparams = list(aH = 2, bH = 2), data = as.matrix(dplyr::select(dt_bact, -c('feature'))), thin = 7, ident = TRUE, burn = 20))

```
